apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend2
  labels:
    {{- include "fastmusik-support.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend2
spec:
  replicas: {{ .Values.frontend2.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend2
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend2
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: frontend2
          image: {{ .Values.frontend2.image }}:{{ .Values.tag }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http