apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-client
  labels:
    {{- include "support-client.labels" . | nindent 4 }}
    app.kubernetes.io/component: support-client
spec:
  replicas: {{ .Values.support-client.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: support-client
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: support-client
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: support-client
          image: {{ .Values.support-client.image }}:{{ .Values.tag }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http