apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastmusik-support
  labels: 
    {{- include "fastmusik-support.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend2
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: apigateway
                port:
                  number: 3000
