apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    {{- include "client.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: client
    app.kubernetes.io/instance: {{ .Release.Name }}