apiVersion: v1
kind: Service
metadata:
  name: support-client
  labels:
    {{- include "support-client.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: support-client
    app.kubernetes.io/instance: {{ .Release.Name }}