apiVersion: v1
kind: Service
metadata:
  name: frontend2
  labels:
    {{- include "fastmusik-support.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: frontend2
    app.kubernetes.io/instance: {{ .Release.Name }}